volumes:
  simply-chic-data:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      DATABASE_URL: postgresql://dev-user:password01@postgres/simply-chic
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: ${SIGNING_KEY}
      SECRET_KEY: ${SECRET_KEY}
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - simply-chic-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password01
      POSTGRES_USER: dev-user
      POSTGRES_DB: simply-chic
    ports:
      - "15432:5432"
  ghi:
    image: node:lts-bullseye
    command: /bin/bash -c "npm i && npm start"
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_HOST}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
